BASE <http://www.example.org>
PREFIX ex:<http://www.example.org>
prefix ex:<http://www.example.org>

SELECT DISTINCT ( ?a + ?b * 1 AS $x )

FROM <www.example.com>
FROM NAMED <www.example.com>

WHERE {
  ?s ?p0 ?o0,?o1 ;
     ?p1 ?o1 .
  (?foo [:p :o] (?bar)) .
  [ a :o ] ?p ?o .
  _:s :p :o
  { ?s ?p ?o }
  { ?s ?p ?o }
  FILTER REGEX(?s, "^foo", "i")
  {} OPTIONAL { ?s ?p ?o }
  optional { ?s ?p ?o }
  { ?s ?p ?o }
  UNION
  { ?s ?p ?o }
}

VALUES ?a {
  <http://example.org/foo>
  <foo>
  example:foo
  'foo'
  "fo\t\\foo\bbo"
  'foo'@de
  'foo'^^<http://example.org/foo>
  '''foo"bar'foo'"'''
  false
  'false'^^xsd:boolean
  1.1
  1.0e6
  '1.3'^^xsd:decimal
}
